name: "Surge CLI Action"
description: "Run Surge command without installing."
branding:
  icon: "terminal"
  color: "green"
author: "Uiolee"
inputs:
  surge-args:
    description: "the command you want to run."
    required: true
    default: "-h"
  surge-token:
    description: "your surge token. It is used to access to surge."
    required: false
    default: ""
  surge-email:
    description: "your surge email. (It is just used to mask your email to prevent it from being displayed in the log of workflow.)"
    required: false
    default: ""
runs:
  using: "node20"
  main: "bundle/index.js"
